### ISSUE TITLE
A solution passed all tests, but not accepted.

### ISSUE THREAD

**Issue by algor512** [exercism/emacs-lisp-test-runner#47]
I get the following result:
![2022-07-08_15-56](https://user-images.githubusercontent.com/446041/177996539-ebe167f9-4684-4167-8f5d-0508fec88b63.png)

What goes wrong? You can see that the solution passed all tests...

The problem: https://exercism.org/tracks/emacs-lisp/exercises/gigasecond

**Comment by iHiD** [comment]
This looks like a bug in the test runner. Could you share your code pls? (cc @ErikSchierboom)

**Comment by algor512** [comment]
Yes, of course:
```
;;; gigasecond.el --- Gigasecond exercise (exercism)

;;; Commentary:
;; Calculate the date one gigasecond (10^9 seconds) from the
;; given date.
;;
;; NB: Pay attention to  Emacs' handling of time zones and dst
;; in the encode-time and decode-time functions.

;;; Code:

(require 'cl-lib)

(defun from (s m h D M Y)
  (cl-subseq (decode-time (time-add (encode-time s m h D M Y)
		  	 (seconds-to-time 1000000000))) 0 6))

(provide 'gigasecond)
;;; gigasecond.el ends here

```
